In [2]:
import pandas as pd
import numpy as np
from pathlib import Path

In [3]:
path = Path("../data/processed/telco_churn_processed.csv")

In [4]:
telco_data = pd.read_csv(path)

In [5]:
telco_data.head().T

,0,1,2,3,4
gender,Female,Male,Male,Male,Female
SeniorCitizen,0,0,0,0,0
Partner,Yes,No,No,No,No
Dependents,No,No,No,No,No
PhoneService,No,Yes,Yes,No,Yes
MultipleLines,No phone service,No,No,No phone service,No
InternetService,DSL,DSL,DSL,DSL,Fiber optic
OnlineSecurity,No,Yes,Yes,Yes,No
OnlineBackup,Yes,No,Yes,No,No
DeviceProtection,No,Yes,No,Yes,No
TechSupport,No,No,No,Yes,No
StreamingTV,No,No,No,No,No
StreamingMovies,No,No,No,No,No
Contract,Month-to-month,One year,Month-to-month,One year,Month-to-month
PaperlessBilling,Yes,No,Yes,No,Yes
PaymentMethod,Electronic check,Mailed check,Mailed check,Bank transfer (automatic),Electronic check
MonthlyCharges,29.85,56.95,53.85,42.3,70.7
TotalCharges,29.85,1889.5,108.15,1840.75,151.65
Churn,No,No,Yes,No,Yes
tenure_group,1-12,25-36,1-12,37-48,1-12

In [6]:
telco_data.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'PhoneService',
       'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup',
       'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies',
       'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges',
       'TotalCharges', 'Churn', 'tenure_group'],
      dtype='object')

In [7]:
telco_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7032 entries, 0 to 7031
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7032 non-null   object
 1   SeniorCitizen     7032 non-null   int64
 2   Partner           7032 non-null   object
 3   Dependents        7032 non-null   object
 4   PhoneService      7032 non-null   object
 5   MultipleLines     7032 non-null   object
 6   InternetService   7032 non-null   object
 7   OnlineSecurity    7032 non-null   object
 8   OnlineBackup      7032 non-null   object
 9   DeviceProtection  7032 non-null   object
 10  TechSupport       7032 non-null   object
 11  StreamingTV       7032 non-null   object
 12  StreamingMovies   7032 non-null   object
 13  Contract          7032 non-null   object
 14  PaperlessBilling  7032 non-null   object
 15  PaymentMethod     7032 non-null   object
 16  MonthlyCharges    7032 non-null   float64
 17  TotalCharges      7032 non-null   float64
 18  Churn             7032 non-null   object
 19  tenure_group      7032 non-null   object
dtypes: float64(2), int64(1), object(17)
memory usage: 1.1+ MB

In [8]:
from sklearn.preprocessing import LabelEncoder

enocoded = LabelEncoder()

In [9]:
#Target column, label encoded
telco_data['Churn'] = enocoded.fit_transform(telco_data['Churn'])

In [10]:
telco_data.nunique()

gender                 2
SeniorCitizen          2
Partner                2
Dependents             2
PhoneService           2
MultipleLines          3
InternetService        3
OnlineSecurity         3
OnlineBackup           3
DeviceProtection       3
TechSupport            3
StreamingTV            3
StreamingMovies        3
Contract               3
PaperlessBilling       2
PaymentMethod          4
MonthlyCharges      1584
TotalCharges        6530
Churn                  2
tenure_group           6
dtype: int64

In [11]:
#Binary categorical columns one hot encoding

binary_categorical = ['gender', 'Partner', 'Dependents', 'PhoneService', 'PaperlessBilling']

binary_telco_data_encoded = pd.get_dummies(telco_data, columns=binary_categorical)

In [12]:
# one hot encoding to all(multi-class categorical, ordinal category, tenure_group)

for_encoding_columns =['MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'PaymentMethod', 'Contract', 'tenure_group']

encoded_telco_data = pd.get_dummies(binary_telco_data_encoded, columns=for_encoding_columns)

In [13]:
encoded_telco_data.head().T

,0,1,2,3,4
SeniorCitizen,0,0,0,0,0
MonthlyCharges,29.85,56.95,53.85,42.3,70.7
TotalCharges,29.85,1889.5,108.15,1840.75,151.65
Churn,0,0,1,0,1
gender_Female,True,False,False,False,True
gender_Male,False,True,True,True,False
Partner_No,False,True,True,True,True
Partner_Yes,True,False,False,False,False
Dependents_No,True,True,True,True,True
Dependents_Yes,False,False,False,False,False
PhoneService_No,True,False,False,True,False
PhoneService_Yes,False,True,True,False,True
PaperlessBilling_No,False,True,False,True,False
PaperlessBilling_Yes,True,False,True,False,True
MultipleLines_No,False,True,True,False,True
MultipleLines_No phone service,True,False,False,True,False
MultipleLines_Yes,False,False,False,False,False
InternetService_DSL,True,True,True,True,False
InternetService_Fiber optic,False,False,False,False,True
InternetService_No,False,False,False,False,False
OnlineSecurity_No,True,False,False,False,True
OnlineSecurity_No internet service,False,False,False,False,False
OnlineSecurity_Yes,False,True,True,True,False
OnlineBackup_No,False,True,False,True,True
OnlineBackup_No internet service,False,False,False,False,False
OnlineBackup_Yes,True,False,True,False,False
DeviceProtection_No,True,False,True,False,True
DeviceProtection_No internet service,False,False,False,False,False
DeviceProtection_Yes,False,True,False,True,False
TechSupport_No,True,True,True,False,True
TechSupport_No internet service,False,False,False,False,False
TechSupport_Yes,False,False,False,True,False
StreamingTV_No,True,True,True,True,True
StreamingTV_No internet service,False,False,False,False,False
StreamingTV_Yes,False,False,False,False,False
StreamingMovies_No,True,True,True,True,True
StreamingMovies_No internet service,False,False,False,False,False
StreamingMovies_Yes,False,False,False,False,False
PaymentMethod_Bank transfer (automatic),False,False,False,True,False
PaymentMethod_Credit card (automatic),False,False,False,False,False
PaymentMethod_Electronic check,True,False,False,False,True
PaymentMethod_Mailed check,False,True,True,False,False
Contract_Month-to-month,True,False,True,False,True
Contract_One year,False,True,False,True,False
Contract_Two year,False,False,False,False,False
tenure_group_1-12,True,False,True,False,True
tenure_group_13-24,False,False,False,False,False
tenure_group_25-36,False,True,False,False,False
tenure_group_37-48,False,False,False,True,False
tenure_group_49-60,False,False,False,False,False
tenure_group_61-72,False,False,False,False,False

In [14]:
encoded_telco_data=encoded_telco_data.astype(int)

In [15]:
output_path = Path("../data/encoded_data/encoded_telco_data.csv")
encoded_telco_data.to_csv(output_path, index=False)

In [17]:
import joblib
joblib.dump(encoded_telco_data, "encoder.pkl")

['encoder.pkl']